# Generated by Django 4.1.3 on 2022-12-30 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_prj', models.CharField(max_length=50, verbose_name='Baslık')),
                ('content_prj', models.TextField(verbose_name='İçerik')),
                ('created_date_ptj', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulduğu tarih')),
                ('proje_image', models.FileField(blank=True, upload_to='', verbose_name='Projeye Foto EKLE')),
                ('author_prj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yazar')),
            ],
        ),
    ]
